import * as ByteBuffer from "bytebuffer";
export declare class Serializer {
    private adapters;
    constructor();
    serialize(obj: any): ByteBuffer;
    private appendOptional;
    private append;
    private chainIdAdapter;
    private stringAdapter;
    private addressAdapter;
    private authorityAdapter;
    private authorityMapAdapter;
    private longAdapter;
    private assetAmountAdapter;
    private bufferAdapter;
    private memoAdapter;
    private voteAdapter;
    private booleanAdapter;
    private optionsAdapter;
    private pubKeyAdapter;
    private publishingAdapter;
    private momentAdapter;
    private blockDataAdapter;
    private transactionAdapter;
    private accountCreateOperationAdapter;
    private accountUpdateOperationAdapter;
    private buyContentOperationAdapter;
    private transferOperationAdapter;
    private coAuthorsAdapter;
    private regionalPriceAdapter;
    private keyPartAdapter;
    private custodyDataAdapter;
    private addContentOperationAdapter;
}
