export enum AccountHistoryOrder {
    TypeAsc = "+type",
    TypeDesc = "-type",
    ToAsc = "+to",
    ToDesc = "-to",
    FromAsc = "+from",
    FromDesc = "-from",
    PriceAsc = "+price",
    PriceDesc = "-price",
    FeeAsc = "+fee",
    FeeDesc = "-fee",
    DescriptionAsc = "+description",
    DescriptionDesc = "-description",
    TimeAsc = "+time",
    TimeDesc = "-time",
}
