export enum OperationType {
    Transfer = 0,
    AccountCreate,
    AccountUpdate,
    AssetCreate,
    AssetIssue,
    AssetPublishFeed = 5,
    MinerCreate,
    MinerUpdate,
    MinerUpdateGlobalParameters,
    ProposalCreate,
    ProposalUpdate = 10,
    ProposalDelete,
    WithdrawPermissionCreate,
    WithdrawPermissionUpdate,
    WithdrawPermissionClaim,
    WithdrawPermissionDelete = 15,
    VestingBalanceCreate,
    VestingBalanceWithdraw,
    Custom,
    Assert,
    ContentSubmit = 20,
    RequestToBuy,
    LeaveRatingAndComment,
    ReadyToPublish,
    ProofOfCustody,
    DeliverKeys = 25,
    Subscribe,
    SubscribeByAuthor,
    AutomaticRenewalOfSubscription,
    ReportStats,
    SetPublishingManager = 30,
    SetPublishingRight,
    ContentCancellation,
    AssetFundPools,
    AssetReserve,
    AssetClaimFees = 35,
    UpdateUserIssuedAsset,
    UpdateMonitoredAsset,
    ReadyToPublishTwo,
    Transfer2,
    UpdateUserIssuedAssetAdvanced = 40,
    NftCreateDefinition,
    NftUpdateDefinition,
    NftIssue,
    NftTransfer,
    NftUpdateData = 45,
    Unknown,
}
